### ISSUE TITLE
Vehicle Maintenance System

### ISSUE THREAD

**Issue by IronMist** [TrainWreckers/Extraction#8]
- Add Conflict's vehicle maintenance system
- Add Conflict's refuel system (jerry cans and refuel points)

**Comment by IronMist** [comment]
- Jerry cans non-operational

**Comment by IronMist** [comment]
Maintenance component added to existing gas pumps with fuel component.

**Comment by IronMist** [comment]
Wrench set to not consume supplies

**Comment by JBraunsmaJr** [comment]
Didn't touch jerrycan but tested on dedicated server and in workbench. Both environments seem to work now.
